version: "3.8"

services:
  # caddy:
  # ngrok:
  # sc-deployer:
  # sc-deployment-server:
  geth:
    image: ethereum/client-go:v1.15.0
    container_name: geth-node
    ports:
      - "8545:8545" # HTTP JSON-RPC
      - "8546:8546" # WebSocket JSON-RPC
      - "30303:30303" # P2P Discovery (TCP)
      - "30303:30303/udp" # P2P Discovery (UDP)
    volumes:
      - ./geth-data:/root/.ethereum
    command:
      - --http
      - --http.addr=0.0.0.0
      - --http.api=eth,net,web3
      - --ws
      - --ws.addr=0.0.0.0
      - --ws.api=eth,net,web3
      - --authrpc.jwtsecret=/root/.ethereum/jwt.hex
      - --datadir=/root/.ethereum
      - --syncmode=snap # 또는 full, light
      - --cache=1024
      - --unlock=0
  geth-init:
    image: ethereum/client-go:v1.15.0
    container_name: geth-init
    depends_on:
      - geth # 'ethereum' 서비스가 시작된 후에 실행
    volumes:
      - ./geth-init:/scripts # 호스트의 geth-init 폴더를 컨테이너의 /scripts 폴더에 연결
    entrypoint: /bin/sh                          # <--- 이 줄을 추가하세요.
    command: -c "/scripts/entrypoint.sh" 
  # graph-ipfs:
  # graph-postgres:
  # graph-redis:
  # graph-node:

  # blockscout: should be another docker-compose.yml file from https://github.com/blockscout/blockscout/tree/master/docker-compose. Don't create a container in this file.